# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Munecting_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireImage'
  pod 'KakaoSDK'


  # Pods for Munecting_iOS

  target 'Munecting_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Munecting_iOSUITests' do
    # Pods for testing
  end

end
